In [46]:
import streamlit as st
import pandas as pd
import numpy as np
import time

import matplotlib.pyplot as plt # plotting library
import seaborn as sns # pretty plotting

sns.set(rc={'figure.figsize':(20,10)})

from sklearn.linear_model import LinearRegression # linear regression package
from sklearn.model_selection import train_test_split # split dataset

from sklearn.linear_model import Lasso

from sklearn.linear_model import Ridge

from sklearn.metrics import mean_squared_error as mse

In [48]:
# insurance_df = pd.read_csv('insurance_regression.csv')
# housing_df = pd.read_csv('data/housing.csv').reset_index()
housing_df = pd.read_csv('data/housing.csv')
housing_df.head(20)

price   area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0   13300000   7420         4          2        3      yes        no       no   
1   12250000   8960         4          4        4      yes        no       no   
2   12250000   9960         3          2        2      yes        no      yes   
3   12215000   7500         4          2        2      yes        no      yes   
4   11410000   7420         4          1        2      yes       yes      yes   
5   10850000   7500         3          3        1      yes        no      yes   
6   10150000   8580         4          3        4      yes        no       no   
7   10150000  16200         5          3        2      yes        no       no   
8    9870000   8100         4          1        2      yes       yes      yes   
9    9800000   5750         3          2        4      yes       yes       no   
10   9800000  13200         3          1        2      yes        no      yes   
11   9681000   6000         4          3        2      yes       yes      yes   
12   9310000   6550         4          2        2      yes        no       no   
13   9240000   3500         4          2        2      yes        no       no   
14   9240000   7800         3          2        2      yes        no       no   
15   9100000   6000         4          1        2      yes        no      yes   
16   9100000   6600         4          2        2      yes       yes      yes   
17   8960000   8500         3          2        4      yes        no       no   
18   8890000   4600         3          2        2      yes       yes       no   
19   8855000   6420         3          2        2      yes        no       no   

   hotwaterheating airconditioning  parking prefarea furnishingstatus  
0               no             yes        2      yes        furnished  
1               no             yes        3       no        furnished  
2               no              no        2      yes    semifurnished  
3               no             yes        3      yes        furnished  
4               no             yes        2       no        furnished  
5               no             yes        2      yes    semifurnished  
6               no             yes        2      yes    semifurnished  
7               no              no        0       no      unfurnished  
8               no             yes        2      yes        furnished  
9               no             yes        1      yes      unfurnished  
10              no             yes        2      yes        furnished  
11             yes              no        2       no    semifurnished  
12              no             yes        1      yes    semifurnished  
13             yes              no        2       no        furnished  
14              no              no        0      yes    semifurnished  
15              no              no        2       no    semifurnished  
16              no             yes        1      yes      unfurnished  
17              no             yes        2       no        furnished  
18              no             yes        2       no        furnished  
19              no             yes        1      yes    semifurnished

In [49]:
columns = ['area','bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea', 'furnishingstatus']
target = ['price']

X = housing_df[columns]
y = housing_df[target]

X_dummies = pd.get_dummies(X)

X_final = X_dummies.drop(['mainroad_no', 'guestroom_no', 'basement_no', 'hotwaterheating_no', 'airconditioning_no', 'prefarea_no'], axis=1)

X_final.head()

area  bedrooms  bathrooms  stories  parking  mainroad_yes  guestroom_yes  \
0  7420         4          2        3        2             1              0   
1  8960         4          4        4        3             1              0   
2  9960         3          2        2        2             1              0   
3  7500         4          2        2        3             1              0   
4  7420         4          1        2        2             1              1   

   basement_yes  hotwaterheating_yes  airconditioning_yes  prefarea_yes  \
0             0                    0                    1             1   
1             0                    0                    1             0   
2             1                    0                    0             1   
3             1                    0                    1             1   
4             1                    0                    1             0   

   furnishingstatus_furnished  furnishingstatus_semifurnished  \
0                           1                               0   
1                           1                               0   
2                           0                               1   
3                           1                               0   
4                           1                               0   

   furnishingstatus_unfurnished  
0                             0  
1                             0  
2                             0  
3                             0  
4                             0

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size = 0.3, random_state = 42)

In [51]:
model = LinearRegression() 

In [52]:
model.fit(X_train, y_train)

LinearRegression()

In [53]:
print(model.score(X_test, y_test))

0.6463350878895877


In [54]:
import joblib

In [55]:
# saving the model
filename = 'model/housing_model3.sav'
joblib.dump(model, filename)

['model/housing_model3.sav']

In [56]:
loaded_model = joblib.load(filename)

In [15]:
loaded_model.predict(X_test)

array([[5372312.61614641],
       [7069241.00525807],
       [3099290.78784024],
       [4526446.61703974],
       [3281573.61192656],
       [3589455.18752547],
       [5728625.30074517],
       [6422877.52476236],
       [2797870.49568591],
       [2554357.99210551],
       [9693560.19894657],
       [2802903.76131031],
       [3026465.95300836],
       [3433891.33202092],
       [3792786.34565513],
       [5321204.36478554],
       [2999852.37322993],
       [4813306.52790376],
       [4572077.61633938],
       [3595733.80237382],
       [5605701.03333098],
       [5838934.41614982],
       [2730716.89440108],
       [4837741.37096246],
       [5638460.49223857],
       [7809681.30410655],
       [3347443.37529207],
       [5328750.6625753 ],
       [8323072.8323739 ],
       [3374792.28854334],
       [6379706.15324898],
       [3397999.89564252],
       [6709115.8233402 ],
       [4249666.18392567],
       [3594972.20315591],
       [5842994.13027721],
       [5115480.11172668],
 

In [14]:
# get coefficients
coefficient = model.coef_

# get intercept
intercept = model.intercept_

In [15]:
coefficient

array([[  261.29692414,   348.90691516,   424.11912829,  -104.81182299,
        23628.36722236,   596.05658924,   109.12197876,  -374.91224933,
         -330.26631867]])

In [16]:
intercept

array([-12865.20866928])

In [18]:
model.score(X_final, y)

0.7506272930769431

In [19]:
y_predicted = model.predict(X_test)

In [16]:
# put coefficients into dataframe
# pair the feature names with the coefficients
coefficients_pd = pd.DataFrame((list(zip(columns, model.coef_ * 1000))), columns = ['Features', 'Coefficients'])

# print table of coefficients for contribution chart
coefficients_pd

Features                                       Coefficients
0     area  [253287.25231305338, 80893141.27100325, 111475...

In [17]:
coefficients_pd.sort_values('Coefficients').set_index('Features').plot(kind = 'barh', color = 'g')

TypeError: no numeric data to plot

In [18]:
# We input new advertising data into the model to predict future sales

# Sample TV, Radio, Newspaper
new_data = [[10, 30, 100]]
model.predict(new_data)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 13 is different from 3)

In [14]:
!pip install pipreqs

In [16]:
!pipreqs